### ISSUE TITLE
2 instances with different baud rates will not receive :-/

### ISSUE THREAD

**Issue by RoboDurden** [ljbeng/SoftwareSerialParity#3]
```
SoftwareSerialParity oSerial(2, 3); // RX, TX
SoftwareSerialParity oSerialD(5, 6); // RX, TX
...
  oSerialD.begin(15625,NONE);
  oSerial.begin(31250,ODD);
...
  if (int iAvail = oSerialD.available())
  {
    // will no longer receive any data :-(
    // if i reverse the two .begin(..) data is received.
  }
```

Greetings from Germany and thank you for the parity fork

**Comment by harryberlin** [comment]
confuse if syntax

**Comment by RoboDurden** [comment]
In the .cpp there are four statics defined, so i guess multiple instances are not possible.
So ein simply made a copy lib SoftwareSeralParity2 but now i get a compile error for the interrupt used multiple times.
I guess i have to actived a different interrupt handler here:

```
#if defined(PCINT0_vect)
ISR(PCINT0_vect)
{
  SoftwareSerialParity2::handle_interrupt();
}
#endif

#if defined(PCINT1_vect)
ISR(PCINT1_vect, ISR_ALIASOF(PCINT0_vect));
#endif

#if defined(PCINT2_vect)
ISR(PCINT2_vect, ISR_ALIASOF(PCINT0_vect));
#endif

#if defined(PCINT3_vect)
ISR(PCINT3_vect, ISR_ALIASOF(PCINT0_vect));
#endif

```

But i don't see where such a `PCINTx_vect` is defined at all :-/

Ideas welcome :-)

**Comment by harryberlin** [comment]
if (oSerialD.available())
  {
    // do what you like
  }

**Comment by RoboDurden** [comment]
:-(

**Comment by ljbeng** [comment]
to use 2 instances, you define 2 ports.  You can transmit from either port anytime. To receive, you must first run a .listen command.

`#include <SoftwareSerialParity.h>
SoftwareSerialParity mySerial(2, 3); // RX, TX
SoftwareSerialParity mySerial1(4, 5); // RX, TX
void setup() {
  // put your setup code here, to run once:
  mySerial.begin(9600,ODD);
  mySerial1.begin(9600,NONE);

   
}

void loop() {
  // put your main code here, to run repeatedly:
  mySerial.println("Hello Worlds");
  delay(1000);
  mySerial1.listen();
  if (mySerial1.available()){
    Serial.write(mySerial1.read());
  }
}`

**Comment by ljbeng** [comment]
and sorry, I don't get any emails on new messages.  I will have to fix that.
